// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251230072758_Add_Bildirim_Mesaj")]
    partial class Add_Bildirim_Mesaj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Entities.Bildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KullaniciId");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mesaj");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("bit")
                        .HasColumnName("OkunduMu");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<short>("Tur")
                        .HasColumnType("smallint")
                        .HasColumnName("Tur");

                    b.Property<string>("VeriJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VeriJson");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId", "OkunduMu");

                    b.ToTable("Bildirimler", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.DenetimKaydi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DetayJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DetayJson");

                    b.Property<string>("Eylem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Eylem");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IpAdresi");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KullaniciId");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("VarlikAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("VarlikAdi");

                    b.Property<string>("VarlikId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("VarlikId");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OlusturmaTarihi");

                    b.ToTable("DenetimKayitlari", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Favori", b =>
                {
                    b.Property<string>("KullaniciId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("KullaniciId");

                    b.Property<int>("IlanId")
                        .HasColumnType("int")
                        .HasColumnName("IlanId");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.HasKey("KullaniciId", "IlanId");

                    b.HasIndex("IlanId");

                    b.ToTable("Favoriler", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Ilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aciklama");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Baslik");

                    b.Property<decimal?>("Boylam")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Boylam");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("Durum");

                    b.Property<decimal?>("Enlem")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("Enlem");

                    b.Property<decimal>("Fiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fiyat");

                    b.Property<int>("GoruntulenmeSayisi")
                        .HasColumnType("int")
                        .HasColumnName("GoruntulenmeSayisi");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("GuncellemeTarihi");

                    b.Property<string>("Ilce")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Ilce");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriId");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OnayTarihi");

                    b.Property<string>("OnaylayanKullaniciId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OnaylayanKullaniciId");

                    b.Property<short>("ParaBirimi")
                        .HasColumnType("smallint")
                        .HasColumnName("ParaBirimi");

                    b.Property<string>("RedNedeni")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RedNedeni");

                    b.Property<string>("SahipKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SahipKullaniciId");

                    b.Property<string>("Sehir")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Sehir");

                    b.Property<string>("SeoSlug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SeoSlug");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit")
                        .HasColumnName("SilindiMi");

                    b.Property<DateTime?>("YayinTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("YayinTarihi");

                    b.HasKey("Id");

                    b.HasIndex("Fiyat");

                    b.HasIndex("OnaylayanKullaniciId");

                    b.HasIndex("SahipKullaniciId");

                    b.HasIndex("KategoriId", "Durum", "OlusturmaTarihi");

                    b.ToTable("Ilanlar", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanAlanDegeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DogruYanlisDeger")
                        .HasColumnType("bit")
                        .HasColumnName("DogruYanlisDeger");

                    b.Property<int>("IlanId")
                        .HasColumnType("int")
                        .HasColumnName("IlanId");

                    b.Property<int>("KategoriAlaniId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriAlaniId");

                    b.Property<string>("MetinDeger")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MetinDeger");

                    b.Property<decimal?>("OndalikDeger")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("OndalikDeger");

                    b.Property<int?>("SecenekId")
                        .HasColumnType("int")
                        .HasColumnName("SecenekId");

                    b.Property<long?>("TamSayiDeger")
                        .HasColumnType("bigint")
                        .HasColumnName("TamSayiDeger");

                    b.Property<DateTime?>("TarihDeger")
                        .HasColumnType("datetime2")
                        .HasColumnName("TarihDeger");

                    b.HasKey("Id");

                    b.HasIndex("SecenekId");

                    b.HasIndex("IlanId", "KategoriAlaniId")
                        .IsUnique();

                    b.HasIndex("KategoriAlaniId", "OndalikDeger");

                    b.HasIndex("KategoriAlaniId", "SecenekId");

                    b.HasIndex("KategoriAlaniId", "TamSayiDeger");

                    b.ToTable("IlanAlanDegerleri", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanCevabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CevapMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CevapMetni");

                    b.Property<string>("CevaplayanKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CevaplayanKullaniciId");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("SoruId")
                        .HasColumnType("int")
                        .HasColumnName("SoruId");

                    b.HasKey("Id");

                    b.HasIndex("CevaplayanKullaniciId");

                    b.HasIndex("SoruId")
                        .IsUnique();

                    b.ToTable("IlanCevaplari", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanFotografi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("DosyaYolu");

                    b.Property<int>("IlanId")
                        .HasColumnType("int")
                        .HasColumnName("IlanId");

                    b.Property<bool>("KapakMi")
                        .HasColumnType("bit")
                        .HasColumnName("KapakMi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("SiraNo");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.ToTable("IlanFotograflari", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanSikayeti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Aciklama");

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("Durum");

                    b.Property<int>("IlanId")
                        .HasColumnType("int")
                        .HasColumnName("IlanId");

                    b.Property<short>("Neden")
                        .HasColumnType("smallint")
                        .HasColumnName("Neden");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("SikayetEdenKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SikayetEdenKullaniciId");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("SikayetEdenKullaniciId");

                    b.ToTable("IlanSikayetleri", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanSorusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Durum")
                        .HasColumnType("smallint")
                        .HasColumnName("Durum");

                    b.Property<int>("IlanId")
                        .HasColumnType("int")
                        .HasColumnName("IlanId");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("SoranKullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SoranKullaniciId");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoruMetni");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("SoranKullaniciId");

                    b.ToTable("IlanSorulari", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Ad");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("AktifMi");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("GuncellemeTarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("SeoSlug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SeoSlug");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit")
                        .HasColumnName("SilindiMi");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("SiraNo");

                    b.Property<int?>("UstKategoriId")
                        .HasColumnType("int")
                        .HasColumnName("UstKategoriId");

                    b.HasKey("Id");

                    b.HasIndex("SeoSlug")
                        .IsUnique();

                    b.HasIndex("UstKategoriId");

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.KategoriAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Ad");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("AktifMi");

                    b.Property<string>("Anahtar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Anahtar");

                    b.Property<bool>("FiltrelenebilirMi")
                        .HasColumnType("bit")
                        .HasColumnName("FiltrelenebilirMi");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriId");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("SiraNo");

                    b.Property<short>("VeriTipi")
                        .HasColumnType("smallint")
                        .HasColumnName("VeriTipi");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("bit")
                        .HasColumnName("ZorunluMu");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KategoriId", "Anahtar")
                        .IsUnique();

                    b.ToTable("KategoriAlanlari", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.KategoriAlaniSecenegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit")
                        .HasColumnName("AktifMi");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Deger");

                    b.Property<int>("KategoriAlaniId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriAlaniId");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int")
                        .HasColumnName("SiraNo");

                    b.HasKey("Id");

                    b.HasIndex("KategoriAlaniId");

                    b.ToTable("KategoriAlanSecenekleri", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.UygulamaKullanicisi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("AdSoyad");

                    b.Property<DateTime?>("AskidaBitisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("AskidaBitisTarihi");

                    b.Property<bool>("AskidaMi")
                        .HasColumnType("bit")
                        .HasColumnName("AskidaMi");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("OlusturmaTarihi");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilFotografYolu")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("ProfilFotografYolu");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2")
                        .HasColumnName("SonGirisTarihi");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Bildirim", b =>
                {
                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "Kullanici")
                        .WithMany("Bildirimler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EntityLayer.Entities.DenetimKaydi", b =>
                {
                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "Kullanici")
                        .WithMany("DenetimKayitlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EntityLayer.Entities.Favori", b =>
                {
                    b.HasOne("EntityLayer.Entities.Ilan", "Ilan")
                        .WithMany("Favoriler")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "Kullanici")
                        .WithMany("Favoriler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EntityLayer.Entities.Ilan", b =>
                {
                    b.HasOne("EntityLayer.Entities.Kategori", "Kategori")
                        .WithMany("Ilanlar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "OnaylayanKullanici")
                        .WithMany()
                        .HasForeignKey("OnaylayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "SahipKullanici")
                        .WithMany("Ilanlar")
                        .HasForeignKey("SahipKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("OnaylayanKullanici");

                    b.Navigation("SahipKullanici");
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanAlanDegeri", b =>
                {
                    b.HasOne("EntityLayer.Entities.Ilan", "Ilan")
                        .WithMany("AlanDegerleri")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.KategoriAlani", "KategoriAlani")
                        .WithMany("IlanAlanDegerleri")
                        .HasForeignKey("KategoriAlaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.KategoriAlaniSecenegi", "Secenek")
                        .WithMany("IlanAlanDegerleri")
                        .HasForeignKey("SecenekId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ilan");

                    b.Navigation("KategoriAlani");

                    b.Navigation("Secenek");
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanCevabi", b =>
                {
                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "CevaplayanKullanici")
                        .WithMany()
                        .HasForeignKey("CevaplayanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.IlanSorusu", "Soru")
                        .WithOne("Cevap")
                        .HasForeignKey("EntityLayer.Entities.IlanCevabi", "SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CevaplayanKullanici");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanFotografi", b =>
                {
                    b.HasOne("EntityLayer.Entities.Ilan", "Ilan")
                        .WithMany("Fotografler")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanSikayeti", b =>
                {
                    b.HasOne("EntityLayer.Entities.Ilan", "Ilan")
                        .WithMany("Sikayetler")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "SikayetEdenKullanici")
                        .WithMany()
                        .HasForeignKey("SikayetEdenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("SikayetEdenKullanici");
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanSorusu", b =>
                {
                    b.HasOne("EntityLayer.Entities.Ilan", "Ilan")
                        .WithMany("Sorular")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", "SoranKullanici")
                        .WithMany()
                        .HasForeignKey("SoranKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("SoranKullanici");
                });

            modelBuilder.Entity("EntityLayer.Entities.Kategori", b =>
                {
                    b.HasOne("EntityLayer.Entities.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("EntityLayer.Entities.KategoriAlani", b =>
                {
                    b.HasOne("EntityLayer.Entities.Kategori", "Kategori")
                        .WithMany("KategoriAlanlari")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("EntityLayer.Entities.KategoriAlaniSecenegi", b =>
                {
                    b.HasOne("EntityLayer.Entities.KategoriAlani", "KategoriAlani")
                        .WithMany("Secenekler")
                        .HasForeignKey("KategoriAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KategoriAlani");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EntityLayer.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Entities.Ilan", b =>
                {
                    b.Navigation("AlanDegerleri");

                    b.Navigation("Favoriler");

                    b.Navigation("Fotografler");

                    b.Navigation("Sikayetler");

                    b.Navigation("Sorular");
                });

            modelBuilder.Entity("EntityLayer.Entities.IlanSorusu", b =>
                {
                    b.Navigation("Cevap");
                });

            modelBuilder.Entity("EntityLayer.Entities.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Ilanlar");

                    b.Navigation("KategoriAlanlari");
                });

            modelBuilder.Entity("EntityLayer.Entities.KategoriAlani", b =>
                {
                    b.Navigation("IlanAlanDegerleri");

                    b.Navigation("Secenekler");
                });

            modelBuilder.Entity("EntityLayer.Entities.KategoriAlaniSecenegi", b =>
                {
                    b.Navigation("IlanAlanDegerleri");
                });

            modelBuilder.Entity("EntityLayer.Entities.UygulamaKullanicisi", b =>
                {
                    b.Navigation("Bildirimler");

                    b.Navigation("DenetimKayitlari");

                    b.Navigation("Favoriler");

                    b.Navigation("Ilanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
